name: Exasol SQLTools Driver

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run npm install
      run: npm install
    - name: Package extension
      uses: lannonbr/vsce-action@master
      with:
        args: "package"
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      shell: bash
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'exasol-driver-*.vsix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ steps.get_version.outputs.VERSION }}
